auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “xiangrumei's Blog”
title: xiangrumei's blog
description: Everything about xiangrumei.
url: http://xiangrumei.github.io
feed: /atom.xml
author_info: <a href="http://xiangrumei.github.io/">xiangrumei</a>
