auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: xiangrumei
url: https://xiangrumei.github.io/
feed: /atom.xml
author_info: <a href="https://xiangrumei.github.io/">xiangrumei</a>
